name: TEST FOR TESTING
env:
  test: ${{ secrets.test }}
on:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: doing nothing
        uses: actions/checkout@v3
